server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp_orz?useSSL=false&serverTimezone=UTC
    username: root
    password: hsp
  redis:
    host: 192.168.226.133
    port: 6379
    password: 12345
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq: # rabbitmq消息队列配置
    host: 192.168.226.133
    port: 5672
    virtual-host: /hmdp
    username: charlie
    password: 123
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug